services:
  - type: web
    name: Text Leech Bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/AshutoshGoswami24/text-leech-bot-for-render
    branch: main
    autoDeploy: false
    envVars:
      - key: 6920570751:AAEzok8WLuEL6Al3jSczzUmGwVyZpHrRrM4
        sync: false
      - key: 29224205
        sync: false
      - key: API_HASH
        sync: false
      - key: WEBHOOK
        sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
